// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BandAid.iOS
{
	public partial class StructureViewController : UIViewController
	{
		public StructureViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
